#!/bin/bash
#SBATCH --job-name=stix-mwa
#SBATCH --partition=performance
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --time=2-00:00:00
#SBATCH --output=z_%J.log
#SBATCH --error=z_%J.log
#SBATCH --exclude=sdas2

/bin/hostname

export PYTHONPATH=/mnt/nas05/clusterdata01/home2/predrag/stix-mwa/src:$PYTHONPATH

/home2/predrag/.conda/envs/stix-mwa/bin/python find_flares_in_mwa.py