#!/bin/bash
#SBATCH --job-name=mwa
#SBATCH --partition=performance
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:1
#SBATCH --time=7-00:00:00
#SBATCH --output=z_%J.log
#SBATCH --error=z_%J.log

/bin/hostname

###export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

source /opt/conda/bin/activate casa_env

srun python get_mwa_data_and_spectrograms.py